import Head from "next/head";
import { useEffect, useState } from "react";
import { io, Socket } from "socket.io-client";
import Chatbox from "../components/Chatbox";
import Composer from "../components/Composer";
import Footer from "../components/Footer";
import {
  ServerToClientEvents,
  ClientToServerEvents,
} from "../../server/socket/types";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [socket, setSocket] =
    useState<Socket<ServerToClientEvents, ClientToServerEvents>>();
  const [messages, setMessages] = useState<Array<string>>([
    "Hi!",
    "Welcome to this chat app!",
    "Type your messages below",
  ]);

  useEffect(() => {
    console.log("Creating socket");
    const socket: Socket<ServerToClientEvents, ClientToServerEvents> = io(
      "http://localhost:3001"
    );
    setSocket(socket);

    socket.on("message", (from: string, message: string) => {
      console.log("Got message", Date.now());
      setMessages((messages) => [...messages, from + ": " + message]);
    });
  }, []);

  if (socket == undefined) {
    return <div> Connecting... </div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>WhutzApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to WhutzApp!</h1>
        <Chatbox socket={socket} messages={messages} />
        <Composer socket={socket} />
      </main>

      <Footer />
    </div>
  );
}
